### ISSUE TITLE
Add the options to choose icon and color

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/generator-github-action-for-marketplace#3]
For Reference, [here](https://actions-cool.github.io/github-action-branding/) is a website that helps to generate them. The expected output will be to add the color and icon to the action.yml generated (for docker and js):

```yml

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'clipboard'
  color: 'red'
```
